name: Build Nobody Client DLL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Nobody Client DLL
        run: msbuild NobodyClient.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v3
        with:
          name: nobody-client-dll
          path: Release\nobodyclient.dll
